# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PerformanceData_Horizon_23.0.0.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PerformanceData_Horizon_23.0.0.proto',
  package='',
  serialized_pb=_b('\n$PerformanceData_Horizon_23.0.0.proto\"l\n\x16PerformanceDataReading\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\r\n\x05owner\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\x04\x12\x10\n\x08\x64\x62lValue\x18\x04 \x03(\x01\x12\x10\n\x08strValue\x18\x05 \x03(\t\"C\n\x17PerformanceDataReadings\x12(\n\x07message\x18\x01 \x03(\x0b\x32\x17.PerformanceDataReadingB3\n\x1aorg.opennms.netmgt.rrd.tcpB\x15PerformanceDataProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERFORMANCEDATAREADING = _descriptor.Descriptor(
  name='PerformanceDataReading',
  full_name='PerformanceDataReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='PerformanceDataReading.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='PerformanceDataReading.owner', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PerformanceDataReading.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dblValue', full_name='PerformanceDataReading.dblValue', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strValue', full_name='PerformanceDataReading.strValue', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=148,
)


_PERFORMANCEDATAREADINGS = _descriptor.Descriptor(
  name='PerformanceDataReadings',
  full_name='PerformanceDataReadings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PerformanceDataReadings.message', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=217,
)

_PERFORMANCEDATAREADINGS.fields_by_name['message'].message_type = _PERFORMANCEDATAREADING
DESCRIPTOR.message_types_by_name['PerformanceDataReading'] = _PERFORMANCEDATAREADING
DESCRIPTOR.message_types_by_name['PerformanceDataReadings'] = _PERFORMANCEDATAREADINGS

PerformanceDataReading = _reflection.GeneratedProtocolMessageType('PerformanceDataReading', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCEDATAREADING,
  __module__ = 'PerformanceData_Horizon_23.0.0_pb2'
  # @@protoc_insertion_point(class_scope:PerformanceDataReading)
  ))
_sym_db.RegisterMessage(PerformanceDataReading)

PerformanceDataReadings = _reflection.GeneratedProtocolMessageType('PerformanceDataReadings', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCEDATAREADINGS,
  __module__ = 'PerformanceData_Horizon_23.0.0_pb2'
  # @@protoc_insertion_point(class_scope:PerformanceDataReadings)
  ))
_sym_db.RegisterMessage(PerformanceDataReadings)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032org.opennms.netmgt.rrd.tcpB\025PerformanceDataProtos'))
# @@protoc_insertion_point(module_scope)
